[package]
name = "flicks2"
version = "0.1.0"
authors = ["Simon Bernier St-Pierre <sbernierstpierre@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1"
csv = "1"
flate2 = "1"
hashbrown = { version = "0.1", features = ["serde"] }
lazy_static = "1"
reqwest = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.8"
strsim = "0.8"
